'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabaseClient';

type Submission = { id:string; business_name:string; city_name:string; state_name:string; street_or_market:string; full_address:string; status:string; created_at:string };

export default function IndiaSubmissionsPage() {
  const [rows,setRows]=useState<Submission[]>([]); const [status,setStatus]=useState('pending'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=async()=>{setLoading(true);setError(''); const {data:admin}=await supabase.rpc('is_admin'); if(!admin){setError('Administrator access required.');setLoading(false);return;} const {data,error}=await supabase.from('india_business_submissions').select('id,business_name,city_name,state_name,street_or_market,full_address,status,created_at').eq('status',status).order('created_at',{ascending:false}); if(error)setError(error.message); setRows((data||[]) as Submission[]);setLoading(false)};
  useEffect(()=>{load()},[status]);
  return <main className="min-h-screen bg-slate-50 px-4 py-10"><div className="mx-auto max-w-6xl"><Link href="/admin" className="font-bold text-blue-700">← Back to Admin</Link><section className="mt-6 rounded-3xl bg-gradient-to-br from-orange-600 to-green-700 p-8 text-white"><p className="text-sm font-bold uppercase tracking-widest">India workflow</p><h1 className="mt-2 text-4xl font-black">Business & location submissions</h1><p className="mt-3 text-white/90">Review the complete address, choose the final browsable location, and approve the street and shop together.</p></section><div className="mt-6 flex gap-2">{['pending','needs_information','approved','rejected'].map(s=><button key={s} onClick={()=>setStatus(s)} className={`rounded-full px-4 py-2 font-bold capitalize ${status===s?'bg-slate-900 text-white':'bg-white text-slate-700'}`}>{s.replace('_',' ')}</button>)}</div>{error&&<div className="mt-6 rounded-2xl bg-red-50 p-4 text-red-700">{error}</div>}{loading?<p className="mt-8">Loading...</p>:<div className="mt-6 grid gap-4">{rows.map(r=><Link key={r.id} href={`/admin/india-submissions/${r.id}`} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm hover:border-orange-300"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><h2 className="text-xl font-black">{r.business_name}</h2><p className="mt-1 font-semibold text-orange-700">{r.street_or_market} · {r.city_name}, {r.state_name}</p><p className="mt-2 text-sm text-slate-600">{r.full_address}</p></div><div className="text-sm text-slate-500">{new Date(r.created_at).toLocaleString()}</div></div></Link>)}{rows.length===0&&<div className="rounded-3xl bg-white p-8 text-center text-slate-600">No {status.replace('_',' ')} submissions.</div>}</div>}</div></main>
}
