import Link from 'next/link';
import { createClient } from '@supabase/supabase-js';

export const revalidate=300;
type Props={params:Promise<{state:string;city:string;street:string;shop:string}>};
const norm=(v:string)=>decodeURIComponent(v||'').toLowerCase().trim().replace(/\s+/g,'-');
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false}});
export default async function IndiaShopPage({params}:Props){
 const p=await params; const ss=norm(p.state),cs=norm(p.city),sts=norm(p.street),shs=norm(p.shop);
 const {data:shop}=await supabase.from('shops').select(`id,name,slug,address,description,parking,category,phone,website,image_url,street:streets!inner(id,name,display_name,slug,city:cities!inner(id,name,slug,state:provinces!inner(id,name,slug,country:countries!inner(slug))))`).eq('slug',shs).eq('approved',true).eq('street.slug',sts).eq('street.city.slug',cs).eq('street.city.state.slug',ss).eq('street.city.state.country.slug','india').maybeSingle();
 if(!shop)return <main className="min-h-screen bg-slate-50 px-4 py-16"><div className="mx-auto max-w-3xl rounded-3xl bg-white p-8"><h1 className="text-3xl font-black">Shop not found</h1></div></main>;
 const street:any=Array.isArray(shop.street)?shop.street[0]:shop.street; const city:any=Array.isArray(street?.city)?street.city[0]:street?.city; const state:any=Array.isArray(city?.state)?city.state[0]:city?.state;
 return <main className="min-h-screen bg-slate-50 px-4 py-12"><div className="mx-auto max-w-5xl"><Link href={`/countries/india/${state.slug}/${city.slug}/streets/${street.slug}`} className="font-bold text-orange-700">← {street.display_name||street.name}</Link><section className="mt-6 overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm">{shop.image_url&&<img src={shop.image_url} alt={shop.name} className="h-64 w-full object-cover"/>}<div className="p-8"><p className="text-sm font-bold uppercase tracking-[0.2em] text-orange-600">{city.name}, {state.name}</p><h1 className="mt-3 text-4xl font-black">{shop.name}</h1>{shop.category&&<p className="mt-2 font-bold text-slate-500">{shop.category}</p>}<p className="mt-6 whitespace-pre-line text-lg leading-8 text-slate-700">{shop.description||'Local business on LocalStreetShop.'}</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-5"><p className="text-sm font-bold text-slate-500">ADDRESS</p><p className="mt-2 font-semibold">{shop.address||'Address not provided'}</p></div><div className="rounded-2xl bg-slate-50 p-5"><p className="text-sm font-bold text-slate-500">ENTRANCE, ACCESS & PARKING</p><p className="mt-2 font-semibold">{shop.parking||'No entrance, access, or parking information provided.'}</p></div></div>{shop.website&&<a href={shop.website} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full bg-orange-600 px-6 py-3 font-bold text-white">Visit website ↗</a>}</div></section></div></main>;
}
